services:
  - type: web
    name: hoja-de-ruta
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: ORS_KEY
        sync: false
      - key: YELP_KEY
        sync: false
